mybatis:
  config-location: classpath:mybatis-config.xml

server:
  port: ${PORT:9090}
spring:
  application:
    name: projectjoa-servicea
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: jdbc:mysql://${SQL_HOST:localhost}:${SQL_PORT:3306}/${SQL_DATABASE:employees}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${SQL_USER:root}
    password: ${SQL_PASSWORD:1234qwer}
        
eureka:
  instance:
    prefer-ip-address: true
    hostname: projectjoa-servicea
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL:127.0.0.1}:${PORT:9065}/eureka