apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectjoa-eureka
  labels:
    app: projectjoa-msa
spec:
  selector:
    matchLabels:
      app: projectjoa-msa 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: projectjoa-msa
        tier: projectjoa-eureka
    spec:
      containers:
        - image: projectjoa/projectjoa-eureka:latest
          imagePullPolicy: Always
          name: projectjoa-eureka
          ports:
            - containerPort: 32065
#            - containerPort: 9065
          env:
          - name: EN_EUREKA_SERVER_URL
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: extenal_ip
          - name: EN_EUREKA_PORT
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: eureka_port
---
apiVersion: v1
kind: Service
metadata:
  name: projectjoa-eureka
  labels:
    app: projectjoa-msa
spec:
  type: NodePort
  ports:
    - port: 32065
      protocol: TCP
      targetPort: 32065
      nodePort: 32065
  selector:
    app: projectjoa-msa
    tier: projectjoa-eureka