apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectjoa-servicea
  labels:
    app: projectjoa-msa
spec:
  selector:
    matchLabels:
      app: projectjoa-msa 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: projectjoa-msa
        tier: projectjoa-servicea
    spec:
      containers:
        - image: projectjoa/projectjoa-servicea:latest
          imagePullPolicy: Always
          name: projectjoa-servicea
          ports:
            - containerPort: 9065
          env:
          - name: EN_EUREKA_SERVER_URL
            value: "172.21.198.42"            
---
apiVersion: v1
kind: Service
metadata:
  name: projectjoa-servicea
  labels:
    app: projectjoa-msa
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30090
  selector:
    app: projectjoa-msa
    tier: projectjoa-servicea