apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectjoa-nginx-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectjoa-nginx-label
  template:
    metadata:
      name: projectjoa-nginx
      labels:
        app: projectjoa-nginx-label
    spec:
      containers:
      - name: projectjoa-nginx
        image: projectjoa/projectjoa-nginx:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          readOnly: true
          name: projectjoa-nginx-conf-pv
          subPath: nginx.conf
      volumes:
      - name: projectjoa-nginx-conf-pv
        configMap:
          name: projectjoa-nginx-configmap
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: projectjoa-nginx-label