apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectjoa-eureka-depl
spec:
  selector:
    matchLabels:
      app: projectjoa-eureka-label
  template:
    metadata:
      name: projectjoa-eureka
      labels:
        app: projectjoa-eureka-label
    spec:
      containers:
        - image: projectjoa/projectjoa-eureka:latest
          name: projectjoa-eureka
          ports:
#            - containerPort: 32065
            - containerPort: 9065
          env:
          - name: EN_EUREKA_SERVER_URL
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: extenal_ip
          - name: EN_EUREKA_PORT
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: eureka_port
---
apiVersion: v1
kind: Service
metadata:
  name: projectjoa-eureka-svc
spec:
  type: NodePort
  ports:
    - port: 9065
      protocol: TCP
      targetPort: 9065
      nodePort: 32065
  selector:
    app: projectjoa-eureka-label