apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectjoa-pyserviceb
  labels:
    app: projectjoa-msa
spec:
  selector:
    matchLabels:
      app: projectjoa-msa
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: projectjoa-msa
        tier: projectjoa-pyserviceb
    spec:
      containers:
        - image: projectjoa/projectjoa-pyserviceb:latest
          imagePullPolicy: Always
          name: projectjoa-pyserviceb
          ports:
          - containerPort: 9094
          env:
          - name: EN_EUREKA_SERVER_URL
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: extenal_ip
          - name: EN_EUREKA_PORT
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: eureka_port
          - name: SQL_HOST
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: mysql_host
          - name: SQL_PORT
            valueFrom:
             configMapKeyRef:
               name: projectjoa-msa-config
               key: mysql_port
          - name: SQL_DATABASE
            valueFrom:
             configMapKeyRef:                         
               name: projectjoa-msa-config            
               key: mysql_database                    
          - name: SQL_USER                
            valueFrom:
              secretKeyRef:
                name: mysql-credential
                key: username       
          - name: SQL_PASSWORD            
            valueFrom:
              secretKeyRef:
                name: mysql-credential
                key: password     
---                                       
apiVersion: v1                            
kind: Service                             
metadata:                                 
  name: projectjoa-pyserviceb               
  labels:                                 
    app: projectjoa-msa                   
spec:                                     
#  type: NodePort                          
  ports:                                  
    - port: 9094                          
      protocol: TCP                       
      targetPort: 9094                    
#      nodePort: 30094                     
  selector:                               
    app: projectjoa-msa                   
    tier: projectjoa-pyserviceb