apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: projectjoa-msa
spec:
  selector:
    matchLabels:
      app: projectjoa-msa
  strategy:
    type: Recreate  
  template:
    metadata:
      labels:
        app: projectjoa-msa
    spec:
      volumes:
      - name: nginx
        configMap:
          name: projectjoa-web-configmap
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: projectjoa-msa
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: projectjoa-msa